### ISSUE TITLE
Superb Work!!!✨

### ISSUE THREAD

**Issue by vasujhawar2001** [nvnt12/codedamn_landing_page#1]
Hi, there. This repo was recommended to me. I was part of the community a while back. And I was just suprised to see this, is this a replica or you have contributed/worked for codedamn. Great work though. It is very inspiring.

**Comment by nvnt12** [comment]
Hello,
Thank you for your kind words! I'm glad you found my project interesting. Just to clarify, it's actually a replica of codedamn's landing page that I created purely for practice and fun—I'm not associated with codedamn in any official capacity.
Your positive feedback is much appreciated and motivating. By the way, I'm curious to know who recommended my project to you. 😄

**Comment by vasujhawar2001** [comment]
It was recommended to me on the GitHub dashboard, appreciate your work. Keep going..💛
